// Generated by CoffeeScript 1.7.1
(function() {
  var Dice, expect;

  expect = require('chai').expect;

  Dice = require('dice').Dice;

  Dice.prototype.Die = require('die').Die;

  describe('Dice', function() {
    var d;
    d = null;
    it('should have at least one die', function() {
      d = new Dice('1d2');
      return expect(d.dice[0].faces).to.equal(2);
    });
    it('should show undefined without dice', function() {
      d = new Dice();
      expect(d.roll()).to.be.undefined;
      return expect(d.get_total()).to.be.undefined;
    });
    return it('should have a suitable score ', function() {
      var i, _i, _results;
      d = new Dice('1d2');
      expect(d.dice[0].score).to.be.above(0);
      expect(d.dice[0].score).to.be.within(1, 2);
      expect(d.dice[0].score).to.be.below(3);
      if (d.get_total() === 2) {
        expect(d.max).to.be["true"];
      } else {
        expect(d.max).to.be["false"];
      }
      _results = [];
      for (i = _i = 1; _i <= 10; i = ++_i) {
        d.roll();
        expect(d.dice[0].score).to.be.above(0);
        expect(d.dice[0].score).to.be.within(1, 2);
        expect(d.dice[0].score).to.be.below(3);
        if (d.get_total() === 2) {
          _results.push(expect(d.max).to.be["true"]);
        } else {
          _results.push(expect(d.max).to.be["false"]);
        }
      }
      return _results;
    });
  });

}).call(this);
