// Generated by CoffeeScript 1.7.1
(function() {
  var Die, expect;

  expect = require('chai').expect;

  Die = require('die').Die;

  describe('Die', function() {
    var d;
    d = null;
    it('should have faces ', function() {
      d = new Die(4);
      return expect(d.faces).to.equal(4);
    });
    return it('should have a suitable score ', function() {
      d = new Die(2);
      expect(d.score).to.be.above(0);
      expect(d.score).to.be.within(1, 2);
      return expect(d.score).to.be.below(3);
    });
  });

}).call(this);
