// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).DicesView = (function() {
    function DicesView(dice, log) {
      this.dice = dice;
      this.log = log;
      return;
    }

    DicesView.prototype.update = function() {};

    DicesView.prototype.roll = function() {
      this.dice.roll();
      this.log(this.dice);
      return this.update();
    };

    return DicesView;

  })();

}).call(this);
