// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).DiceView = (function() {
    function DiceView(parent, dice) {
      this.parent = parent;
      this.dice = dice;
      this.view = new View(this.parent);
      this.form = this.view.form({
        id: 'dice_form'
      });
      this["in"] = this.view.input({
        id: 'dice_in',
        parent: this.form
      });
      this.sub = this.view.input({
        id: 'dice_sub',
        type: 'submit',
        parent: this.form
      });
      this.sub.onclick = (function(_this) {
        return function() {
          _this.roll();
          return false;
        };
      })(this);
      this.out = this.view.div({
        id: 'dice_out',
        parent: this.form
      });
    }

    DiceView.prototype.update = function() {
      var tot;
      tot = this.dice.get_total();
      if (parseInt(tot, 10) === tot) {
        this.view.div({
          innerHTML: this.dice.get_total(),
          parent: this.out
        });
      }
    };

    DiceView.prototype.roll = function() {
      console.log(this["in"].value);
      this.dice.roll(this["in"].value);
      console.log(this.dice);
      return this.update();
    };

    return DiceView;

  })();

}).call(this);
