// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).DicesView = (function() {
    function DicesView(id, up_e, dice) {
      this.up_e = up_e;
      this.dice = dice;
      this.views = [];
      this.up = new View(this.up_e);
      this.con = this.up["new"]({
        element: 'div',
        id: "dices" + id,
        className: 'dices'
      });
      this.view = new View(this.con);
      this.form = this.view["new"]({
        element: 'form',
        className: 'dices_form'
      });
      this["in"] = this.view["new"]({
        element: 'input',
        className: 'dices_in',
        parent: this.form
      });
      this.sub = this.view["new"]({
        element: 'input',
        className: 'dices_sub',
        type: 'submit',
        parent: this.form
      });
      this.sub.value = 'Create Dice';
      this.out = this.view["new"]({
        element: 'div',
        id: 'dice'
      });
      this.sub.onclick = (function(_this) {
        return function() {
          _this.add_dice();
          return false;
        };
      })(this);
    }

    DicesView.prototype.add_dice = function() {
      var dice;
      dice = new this.dice(this["in"].value);
      if (dice.is_good()) {
        return this.views.push(new DiceView(this.views.length, this, this.out, dice));
      }
    };

    DicesView.prototype.remove_dice = function(dice_view) {
      this.views[dice_view.id] = void 0;
      return dice_view = void 0;
    };

    return DicesView;

  })();

}).call(this);
