// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).DiceView = (function() {
    function DiceView() {
      return;
    }

    return DiceView;

  })();

}).call(this);
