// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Die = (function() {
    function Die(faces) {
      this.faces = faces;
      this.faces = parseInt(this.faces, 10);
      this.roll();
    }

    Die.prototype.roll = function() {
      if (!this.faces) {
        return;
      }
      return this.score = 1 + Math.floor((Math.random() * this.faces) / 1);
    };

    return Die;

  })();

}).call(this);
