// Generated by CoffeeScript 1.7.1
(function() {
  var $0x3e;

  $0x3e = (typeof exports !== "undefined" && exports !== null) && exports || (this.$0x3e = {});

  $0x3e.Die = (function() {
    function Die(faces) {
      this.faces = faces;
      this.faces = parseInt(this.faces, 10);
      this.score = this.roll();
      return;
    }

    Die.prototype.roll = function() {
      if (!this.faces) {
        return;
      }
      return 1 + Math.floor(Math.random() * this.faces);
    };

    return Die;

  })();

}).call(this);
