// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Die = (function() {
    function Die(faces) {
      this._faces = parseInt(faces, 10);
      this.roll();
    }

    Die.prototype.roll = function() {
      if (!this._faces) {
        return;
      }
      return this._score = 1 + Math.floor((Math.random() * this._faces) / 1);
    };

    Die.prototype.get_faces = function() {
      return this._faces;
    };

    Die.prototype.get_score = function() {
      return this._score;
    };

    return Die;

  })();

}).call(this);
