// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Main = (function() {
    function Main() {
      window.onload = function() {
        var dice, dice_div, dice_view, view;
        dice = new Dice();
        view = new View(document.body);
        dice_div = view.div({
          id: 'dice1'
        });
        dice_view = new DiceView(dice_div, dice);
      };
      return;
    }

    return Main;

  })();

}).call(this);
