// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Main = (function() {
    function Main() {
      window.onload = (function(_this) {
        return function() {
          var dice, dices_div;
          dice = Dice;
          _this.view = new View(document.body);
          dices_div = view["new"]({
            element: 'div',
            id: 'dices'
          });
          _this.dices_view = new DicesView(0, dices_div, dice);
        };
      })(this);
      return;
    }

    return Main;

  })();

}).call(this);
