// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Store = (function() {
    function Store() {}

    Store.set = function(key, value) {
      localStorage.setItem(key, value);
    };

    Store.set_cookie = function(key, value) {
      var d, expires;
      expires = void 0;
      d = void 0;
      d = new Date();
      d.setTime(d.getTime() + (365 * 24 * 60 * 60 * 1000));
      expires = "; expires=" + d.toGMTString();
      document.cookie = key + "=" + value + "; expires=" + expires + " path=/";
    };

    Store.get = function(key) {
      return localStorage.getItem(key);
    };

    Store.get_cookie_value = function(name) {
      var cookie, i, length, split_keys, split_values;
      i = void 0;
      split_keys = void 0;
      cookie = void 0;
      split_values = void 0;
      length = void 0;
      cookie = document.cookie;
      split_values = cookie.split(";");
      length = split_values.length;
      i = 0;
      while (i < length) {
        split_keys = split_values[i].split("=");
        split_keys[0] = split_keys[0].replace(/^ /, "");
        if (split_keys[0] === name) {
          return split_keys[1];
        }
        i += 1;
      }
      return "";
    };

    return Store;

  })();

}).call(this);
