// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty;

  (typeof exports !== "undefined" && exports !== null ? exports : this).View = (function() {
    View.prototype.document = (typeof document !== "undefined" && document !== null) && document;

    function View(view_container) {
      this.view_container = view_container;
      this.document = (View.prototype.document != null) && View.prototype.document || (this.document = document);
    }

    View.prototype["new"] = function(ob) {
      var el, k, v;
      el = this.document.createElement(ob.element);
      if (k !== 'parent') {
        for (k in ob) {
          if (!__hasProp.call(ob, k)) continue;
          v = ob[k];
          el[k] = v;
        }
      }
      if (ob.parent) {
        ob.parent.appendChild(el);
      } else {
        this.view_container.appendChild(el);
      }
      return el;
    };

    View.prototype.remove = function(el) {
      this.empty(el);
      el.parentElement.removeChild(el);
    };

    View.prototype.empty = function(el) {
      while (el.firstChild) {
        el.removeChild(el.firstChild);
      }
    };

    return View;

  })();

}).call(this);
