// Generated by CoffeeScript 1.7.1
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).View = (function() {
    function View(view_container) {
      this.view_container = view_container;
      return;
    }

    View.prototype.div = function(ob) {
      ob.element = 'div';
      return this.el(ob);
    };

    View.prototype.span = function(ob) {
      ob.el = 'span';
      return this.el(ob);
    };

    View.prototype.form = function(ob) {
      ob.element = 'form';
      return this.el(ob);
    };

    View.prototype.input = function(ob) {
      var el;
      ob.element = 'input';
      el = this.el(ob);
      if (ob.type) {
        el.type = ob.type;
      }
      return el;
    };

    View.prototype.el = function(ob) {
      var el;
      el = document.createElement(ob.element);
      if (ob.id) {
        el.id = ob.id;
      }
      if (ob["class"]) {
        el.className = ob["class"];
      }
      if (ob.classes) {
        el.className += ob.classes;
      }
      if (ob.innerHTML) {
        el.innerHTML = ob.innerHTML;
      }
      if (ob.parent) {
        ob.parent.appendChild(el);
      } else {
        this.view_container.appendChild(el);
      }
      return el;
    };

    View.prototype.hide = function() {
      this.view_container.style.display = 'none';
    };

    View.prototype.show = function() {
      this.view_container.style.display = 'block';
    };

    View.prototype.remove = function(el) {
      el.parentElement.removeChild(el);
    };

    return View;

  })();

}).call(this);
